import type { PosterState } from '@/types/poster';
import { nanoid } from 'nanoid';

export const ASPECTS: Record<string, { w: number; h: number }> = {
  '1:1': { w: 1080, h: 1080 },
  '4:5': { w: 1080, h: 1350 },
  '9:16': { w: 1080, h: 1920 },
};

export const PALETTE = {
  void: '#0A0908',
  paper: '#EFEAE0',
  ash: '#7A776F',
  blood: '#A8202C',
  ink: '#000000',
  gauze: '#D6D1C4',
};

export const SWATCHES = Object.values(PALETTE);

export const defaultPreset = (): PosterState => ({
  source: {
    imageDataUrl: null,
    imageName: null,
    imageW: 0,
    imageH: 0,
    offsetX: 0,
    offsetY: 0,
    scale: 1,
    rotation: 0,
    fitMode: 'contain',
  },
  dither: {
    algorithm: 'floyd-steinberg',
    pixelScale: 8,
    threshold: 128,
    levels: 2,
    preBlur: 0,
    contrast: 1.1,
    brightness: 0,
    gamma: 1,
    invert: false,
    serpentine: true,
  },
  color: {
    background: PALETTE.void,
    foreground: PALETTE.gauze,
    accent: PALETTE.blood,
    mode: 'mono',
    duotoneRamp: 0.5,
    blendMode: 'normal',
    imageOpacity: 1,
  },
  layout: {
    aspect: '4:5',
    width: ASPECTS['4:5'].w,
    height: ASPECTS['4:5'].h,
    marginTop: 56,
    marginRight: 56,
    marginBottom: 56,
    marginLeft: 56,
    gridOverlay: false,
    safeArea: false,
    asymmetry: 0,
  },
  text: [
    {
      id: nanoid(6),
      content: 'HOMME PLUS',
      font: 'mono',
      size: 18,
      weight: 700,
      tracking: 0.18,
      leading: 1.1,
      color: PALETTE.paper,
      align: 'left',
      upper: true,
      x: 0.08,
      y: 0.06,
      rotation: 0,
      visible: true,
    },
    {
      id: nanoid(6),
      content: 'COLLECTION / FW26',
      font: 'mono',
      size: 10,
      weight: 400,
      tracking: 0.18,
      leading: 1.1,
      color: PALETTE.ash,
      align: 'left',
      upper: true,
      x: 0.08,
      y: 0.1,
      rotation: 0,
      visible: true,
    },
    {
      id: nanoid(6),
      content: '川久保 玲',
      font: 'jp-serif',
      size: 56,
      weight: 700,
      tracking: 0.04,
      leading: 1,
      color: PALETTE.paper,
      align: 'right',
      upper: false,
      x: 0.92,
      y: 0.84,
      rotation: 0,
      visible: true,
    },
    {
      id: nanoid(6),
      content: 'NOISE / SIGNAL / SILHOUETTE',
      font: 'mono',
      size: 10,
      weight: 400,
      tracking: 0.18,
      leading: 1.1,
      color: PALETTE.ash,
      align: 'right',
      upper: true,
      x: 0.92,
      y: 0.94,
      rotation: 0,
      visible: true,
    },
  ],
  hud: {
    corners: {
      tl: { enabled: true, label: 'FRAME', value: '01 / 04', accent: false },
      tr: { enabled: true, label: 'CHANNEL', value: 'HP.FW26', accent: true },
      bl: { enabled: true, label: 'STATUS', value: 'ARCHIVED', accent: false },
      br: { enabled: true, label: 'INDEX', value: 'CDG ⁄ 0044', accent: false },
    },
    ticks: {
      enabled: true,
      count: 80,
      yPercent: 0.78,
      leftLabel: 'SYNC',
      rightLabel: 'EXPORT',
    },
    checklist: {
      enabled: true,
      items: [
        'STORYBOARD READY',
        'IMAGE READY',
        'AGENCY APPROVED',
        'ON SCHEDULE',
        'ON BUDGET',
      ],
      xPercent: 0.08,
      yPercent: 0.74,
    },
    stripes: {
      enabled: true,
      count: 2,
      width: 80,
      height: 36,
      angle: -45,
    },
    registration: { enabled: false, size: 14 },
    pagination: { enabled: true, count: 14, active: 4 },
    plusMark: { enabled: true, size: 18 },
    barcode: { enabled: false, width: 120, height: 24 },
    frame: { enabled: false, stroke: 1, inset: 8 },
  },
  finish: {
    grainAmount: 0.06,
    grainSize: 1,
    scanlines: 0,
    scanSpacing: 2,
    vignette: 0,
    halftoneAmount: 0,
    halftoneRadius: 2,
  },
});
